# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ci_code_check
    displayName: CI - Kód ellenőrzés
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: basic_check
        displayName: Alap ellenőrzés
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"
          - script: |
              ls -l
              sudo npm install
                            
              echo "##[command]A kód rendben?"
              npm run lint:js
              commandresult=$(echo $?)    
              echo "##[debug]Kód ellenőrzés eredménye: $commandresult"
              if [[ $commandresult != 0 ]];
              then
                echo "##vso[task.complete result=Failed;]A kódban hiba található!"
              fi
            displayName: "NodeJS - Kód ellenőrzés"
          - script: |
              sudo npm install
                          
              echo "##[command]A kód rendben?"
              npm run lint:ejs
              commandresult=$(echo $?)    
              echo "##[debug]Kód ellenőrzés eredménye: $commandresult"
              if [[ $commandresult != 0 ]];then
                echo "##vso[task.complete result=Failed;]A kódban hiba található!"
              fi
            displayName: "EJS - Kód ellenőrzés"
