# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ci_code_check
    displayName: CI - Kód ellenőrzés
    condition: eq(variables['Build.Reason'], 'PullRequest')
    jobs:
      - job: basic_check
        displayName: Kód ellenőrzés
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"
          - task: Bash@3
            name: install_dependencies
            displayName: Függőségek teleptése
            inputs:
              targetType: "inline"
              script: |
                npm upgrade
                npm install
          - task: Bash@3
            name: node_check
            displayName: "NodeJS - Kód ellenőrzés"
            inputs:
              targetType: "inline"
              script: |
                echo "##[command]A kód rendben?"
                npm run lint:js
          - task: Bash@3
            name: ejs_check
            displayName: "EJS - Kód ellenőrzés"
            inputs:
              targetType: "inline"
              script: |
                echo "##[command]A kód rendben?"
                npm run lint:ejs

