# This is a basic workflow to help you get started with Actions

name: CI (continuous integration)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "*"
      - "!main"
      - "!demo"
  pull_request:
    branches:
      - main
      - demo

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Kód és funkció ellenőrzés
    if: github.event_name == 'pull_request'
    steps:
      - name: Kód letöltés
        uses: actions/checkout@v4
      - name: Node.js beállítás
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Node - Csomagkezelő frissítés
        run: npm upgrade
      - name: Node - Függőségek telepítése
        run: npm install
      - name: Node - 'js' fájlok ellenőrzése
        run: npm run lint:js
      - name: Node - 'ejs' fájlok ellenőrzése
        run: npm run lint:ejs
      - name: Node - Tesztesetek futtatása
        run: npm run test
